<?php
$labels = array();
$labels['notes'] = 'Notizen';
$labels['note_new'] = 'Neu';
$labels['note_edit'] = 'Bearbeiten';
$labels['note_rename'] = 'Umbenennen';
$labels['note_del'] = 'Löschen';
$labels['note_send'] = 'Senden';
$labels['note_upload'] = 'Hochladen';
$labels['note_title'] = 'Name für Notiz';
$labels['note_tags'] = 'Kommagetrennte Tagliste';
$labels['note_inv_format'] = 'Nicht unterstütztes Notiz Format!';
$labels['note_del_note'] = 'Möchten Sie "%note%" wirklich löschen?';
$labels['note_subject'] = 'Per E-Mail senden: ';
$labels['note_formathtml'] = 'HTML';
$labels['note_formatmd'] = 'Markdown';
$labels['note_formattxt'] = 'Normaler Text';
$labels['ariallabelnewoptions'] = 'Optionen';
?>