<?php
$labels = array();
$labels['notes'] = 'Notes';
$labels['note_new'] = 'New';
$labels['note_edit'] = 'Edit';
$labels['note_rename'] = 'Rename';
$labels['note_del'] = 'Delete';
$labels['note_send'] = 'Send';
$labels['note_upload'] = 'Upload';
$labels['note_title'] = 'Name for Note';
$labels['note_tags'] = 'Comma Separated Taglist';
$labels['note_inv_format'] = 'Unsupported note format!';
$labels['note_del_note'] = 'Do you really want to delete "%note%"?';
$labels['note_subject'] = 'Send by e-mail: ';
$labels['note_formathtml'] = 'HTML';
$labels['note_formatmd'] = 'Markdown';
$labels['note_formattxt'] = 'Pure Text';
$labels['ariallabelnewoptions'] = 'Options';
?>