<?php
$labels = array();
$labels['notes'] = 'Notas';
$labels['note_new'] = 'Nueva';
$labels['note_edit'] = 'Editar';
$labels['note_rename'] = 'Renombrar';
$labels['note_del'] = 'Eliminar';
$labels['note_send'] = 'Enviar';
$labels['note_upload'] = 'Subir';
$labels['note_title'] = 'Nombre de la Nota';
$labels['note_tags'] = 'Separar por comas las etiquetas';
$labels['note_inv_format'] = 'Formato de nota no soportado!';
$labels['note_del_note'] = 'Realmente desea eliminar la nota : "%note%"?';
$labels['note_subject'] = 'Enviar por correo: ';
$labels['note_formathtml'] = 'HTML';
$labels['note_formatmd'] = 'Markdown';
$labels['note_formattxt'] = 'Texto Plano';
$labels['ariallabelnewoptions'] = 'Opciones';
?>