<?php
$labels['notes'] = 'Märkmed';
$labels['note_new'] = 'Uus';
$labels['note_show'] = 'Näita';
$labels['note_edit'] = 'Muuda';
$labels['note_rename'] = 'Muuda nime';
$labels['note_del'] = 'Kustuta';
$labels['note_send'] = 'Saada';
$labels['note_upload'] = 'Laadi üles';
$labels['note_download'] = 'Laadi alla';
$labels['note_title'] = 'Märkme nimi';
$labels['note_tags'] = 'Komadega eraldatud siltide loend';
