<?php
$labels = array();
$labels['notes'] = 'Notas';
$labels['note_new'] = 'Nova';
$labels['note_edit'] = 'Editar';
$labels['note_rename'] = 'Renomear';
$labels['note_del'] = 'Deletar';
$labels['note_send'] = 'Compartilhar';
$labels['note_upload'] = 'Upload';
$labels['note_title'] = 'Nome para a nota';
$labels['note_tags'] = 'Tags separadas por vírgula';
$labels['note_inv_format'] = 'Formato de nota não suportado !';
$labels['note_del_note'] = 'Deseja mesmo remover "%note%" ?';
$labels['note_subject'] = 'Enviando por e-mail: ';
$labels['note_formathtml'] = 'HTML';
$labels['note_formatmd'] = 'Remarcar';
$labels['note_formattxt'] = 'Texto puro';
$labels['ariallabelnewoptions'] = 'Opções';
?>
