<?php
$labels = array();
$labels['notes'] = 'Заметки';
$labels['note_new'] = 'Новая заметка';
$labels['note_edit'] = 'Изменить';
$labels['note_rename'] = 'Переименовать';
$labels['note_del'] = 'Удалить';
$labels['note_send'] = 'Отправить';
$labels['note_upload'] = 'Импортировать';
$labels['note_title'] = 'Название заметки';
$labels['note_tags'] = 'Теги через запятую';
$labels['note_inv_format'] = 'Неподдерживаемый формат заметок!';
$labels['note_del_note'] = 'Вы действительно хотите удалить "%note%"?';
$labels['note_subject'] = 'Заметка: ';
$labels['note_formathtml'] = 'HTML заметка';
$labels['note_formatmd'] = 'Простая заметка';
$labels['note_formattxt'] = 'Текстовая заметка';
$labels['ariallabelnewoptions'] = 'Параметры';
?>