<?php
$labels = array();
$labels['notes'] = 'Заметки';
$labels['note_new'] = 'Новая заметка';
$labels['note_edit'] = 'Изменить';
$labels['note_rename'] = 'Переименовать';
$labels['note_del'] = 'Удалить';
$labels['note_send'] = 'Отправить';
$labels['note_upload'] = 'Импортировать';
$labels['note_title'] = 'Название заметки';
$labels['note_tags'] = 'Теги через запятую';
$labels['note_inv_format'] = 'Неподдерживаемый формат заметок!';
$labels['note_del_note'] = 'Вы действительно хотите удалить "%note%"?';
$labels['note_subject'] = 'Заметка: ';
$labels['note_formathtml'] = 'HTML заметка';
$labels['note_formatmd'] = 'Простая заметка';
$labels['note_formattxt'] = 'Текстовая заметка';
$labels['note_formatpdf'] = 'Adobe PDF';
$labels['note_formatjpg'] = 'JPG';
$labels['note_formatpng'] = 'PNG';
$labels['ariallabelnewoptions'] = 'Параметры';
$labels['note_defaultformat'] = 'Стандартный формат';
$labels['note_listformat'] = 'Displayed Formats';
$labels['note_yamls'] = 'Активировать YAML';
$labels['note_rmedia_md'] = 'Автоматическое удаление встроенного мультимедиа с помощью файлов Markdown';
?>